In [1]:
# sistemas de recomendación
# factorización de matriz de interacción  SVD
# Podemos usar A estimada para predecir valores de recomendación
import numpy as np
#datos de entrada
A = np.array([
    [5, 3, 0, 4],
    [4, 0, 0, 0],
    [0, 5, 4, 0],
    [0, 0, 0, 5]
])
# descomposición en valores singulares (SVD) 
# A = U x Σ x V^T
# A: matriz de calificaciones
# U: matriz de características de usuarios (U).
# V: matriz de características de elementos (V).
# Σ: matriz diagonal de valores singulares (Σ). 
# La matriz Σ contiene información sobre la importancia relativa de cada característica.

U, Sigma, Vt = np.linalg.svd(A)

In [2]:
print(U)

[[-0.80927637 -0.21185422 -0.1538383  -0.52585485]
 [-0.28599399 -0.19755527 -0.62195328  0.70167904]
 [-0.38422382  0.89455109  0.11507344  0.19725241]
 [-0.34007536 -0.34039398  0.75912186  0.43842295]]


In [3]:
print(Sigma)

[8.52020793 6.11944351 4.57678278 1.00574717]


In [4]:
print(Vt)

[[-0.60918206 -0.51042747 -0.18038237 -0.57950256]
 [-0.30223209  0.6270493   0.58472708 -0.41660435]
 [-0.71163627  0.02487605  0.10057146  0.69486717]
 [ 0.17642793 -0.58792359  0.784501    0.08818853]]


In [5]:
k = 2  # Número de características a conservar

U_k = U[:, :k]
Sigma_k = np.diag(Sigma[:k])
Vt_k = Vt[:k, :]

In [6]:
print(Vt_k)

[[-0.60918206 -0.51042747 -0.18038237 -0.57950256]
 [-0.30223209  0.6270493   0.58472708 -0.41660435]]


In [7]:
A_estimada = np.dot(np.dot(U_k, Sigma_k), Vt_k)

print("Matriz de calificaciones estimadas:")
print(A_estimada)

Matriz de calificaciones estimadas:
[[ 4.59225663  2.70657556  0.48571536  4.53588607]
 [ 1.84978805  0.48571536 -0.26735033  1.91573504]
 [ 0.33979388  5.10353447  3.79139836 -0.38345838]
 [ 2.3946688   0.17281282 -0.69533899  2.54691198]]


In [ ]:
# puede probar otras descomposiciones y cálculo de A estimadas por:
# Descomposición QR: se enfoca en encontrar una matriz ortogonal Q y una matriz triangular superior R
# que al multiplicarse se aproximen a la matriz original A

# Factorización no negativa de matrices (NMF): descomponer una matriz A en dos matrices W y H
# tales que todas las entradas de W y H sean no negativas. 
# Esta técnica es útil en sistemas de recomendación donde se busca tener valores no negativos 
# en las matrices de características de usuarios y elementos.

# Factorización de matrices probabilísticas (PMF):  se modela cada entrada de la matriz de calificaciones 
# como una distribución de probabilidad condicional de dos variables latentes: una para el usuario y otra 
# para el elemento. Estas distribuciones se multiplican para obtener la probabilidad conjunta de una 
# calificación. Luego, se maximiza la probabilidad conjunta utilizando métodos de optimización 
# para ajustar los parámetros de las matrices de características de usuario y elemento.
